### ISSUE TITLE
Using ayon-coio in dev mode

### ISSUE THREAD

**Issue by MustafaJafar** [ynput/ayon-ocio#4]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

AYON launcher is not able to find the ocio config file location when using `ayon-coio` in dev mode because the launcher expects the config file to exist inside the client code.

```
*** WRN: >>> { ayon_core.pipeline.colorspace }: [  Path was not found 'E:\Ynput\ayon-ocio\client\ayon_ocio\configs\OpenColorIOConfigs\aces_1.2\config.ocio'.  ] 
*** WRN: >>> { ActionsModel }: [  Action trigger FAILED.  ]
==============================
No OCIO config found in settings. It is either missing or there is typo in path inputs
==============================
Traceback (most recent call last):
  File "E:\Ynput\ayon-core\client\ayon_core\tools\launcher\models\actions.py", line 405, in trigger_action
    action.process(selection)
  File "E:\Ynput\ayon-applications\client\ayon_applications\action.py", line 126, in process
    self.application.launch(
  File "E:\Ynput\ayon-applications\client\ayon_applications\defs.py", line 298, in launch
    return self.manager.launch(self.full_name, *args, **kwargs)
  File "E:\Ynput\ayon-applications\client\ayon_applications\manager.py", line 173, in launch
    return self.launch_with_context(context)
  File "E:\Ynput\ayon-applications\client\ayon_applications\manager.py", line 149, in launch_with_context
    return launch_context.launch()
  File "E:\Ynput\ayon-applications\client\ayon_applications\manager.py", line 597, in launch
    self.run_prelaunch_hooks()
  File "E:\Ynput\ayon-applications\client\ayon_applications\manager.py", line 581, in run_prelaunch_hooks
    prelaunch_hook.execute()
  File "E:\Ynput\ayon-core\client\ayon_core\hooks\pre_ocio_hook.py", line 39, in execute
    config_data = get_imageio_config_preset(
  File "E:\Ynput\ayon-core\client\ayon_core\pipeline\colorspace.py", line 983, in get_imageio_config_preset
    raise FileExistsERROR(
FileExistsERROR: No OCIO config found in settings. It is either missing or there is typo in path inputs
```

### Expected Behavior:

to have `client/ayon_ocio/configs` in git ignore. 
Being able to run some installation script that downloads the configs to the client code dir.

### Version

1.0.0

### What platform you are running on?

Windows

### Steps To Reproduce:

1. in your dev bundle, toggle addon directory for `ayon-ocio`
2. add your ayon-ocio/client location
3. run any application through launcher

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

**Comment by jakubjezek001** [comment]
Hi @MustafaJafar is this still relevant? It seems this issue can be closed. Reopen it in case your tests will not go well. Thank you.

**Comment by MustafaJafar** [comment]
It's still relevant. I actually solved it by extracting the downloaded files to `client/ayon_ocio/configs` and added that path to `.gitignore`. 
I don't think we need to re-open it.
